# Generated by Django 4.1.5 on 2023-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('foundation', 'Fundacja'), ('nongovorg', 'Organizacja pozarządowa'), ('local', 'zbiórka lokalna')], default='foundation', max_length=40)),
                ('categories', models.ManyToManyField(to='share.category')),
            ],
        ),
    ]
