# Generated by Django 4.1.5 on 2023-01-13 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('categories', models.ManyToManyField(to='share.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
